from enum import Enum


class OrderTypes(str, Enum):
    REMISSION = "REMISSION"


class RemissionEvents(str, Enum):
    INTEGRATED = "INTEGRATED"
    RECEIPT_CONFIRMED = "RECEIPT_CONFIRMED"
    PICKING_COMPLETED = "PICKING_COMPLETED"
    DISPATCHED = "DISPATCHED"
    TRANSPORT_ARRIVAL = "TRANSPORT_ARRIVAL"
    PARTIAL_WITH_REJECTION = "PARTIAL_WITH_REJECTION"
    PARTIAL_COMPLETE = "PARTIAL_COMPLETE"
    COMPLETE = "COMPLETE"
    REJECTED = "REJECTED"


class RemissionMigrationOrigins(str, Enum):
    FIRESTORE = "FIRESTORE"
    BLUEYONDER = "BLUEYONDER"


class RemissionEventWarnings(str, Enum):
    MANUALLY_DELIVERED = "MANUALLY_DELIVERED"
