from enum import Enum


class OmsEntityTypes(str, Enum):
    REMISSION_PISA = "REMISSION_PISA"


class RemissionEvents(str, Enum):
    ORDER_ACCEPTED = "ORDER_ACCEPTED"
    ORDER_CREATED = "ORDER_CREATED"
    ORDER_REJECTED = "ORDER_REJECTED"
    ORDER_SCHEDULED = "ORDER_SCHEDULED"
    ORDER_FULFILLED = "ORDER_FULFILLED"
    ORDER_VALIDATED = "ORDER_VALIDATED"
    ORDER_ON_TRANSPORT = "ORDER_ON_TRANSPORT"
    ORDER_DISPATCHED = "ORDER_DISPATCHED"
    EN_ROUTE_TO_DROPOFF = "EN_ROUTE_TO_DROPOFF"
    TRANSPORT_ARRIVED = "TRANSPORT_ARRIVED"
    DELIVERY_COMPLETED = "DELIVERY_COMPLETED"
    DELIVERY_REJECTED = "DELIVERY_REJECTED"
    OFFICE_EVIDENCE_RECEIVED = "OFFICE_EVIDENCE_RECEIVED"
